name: flutter_application
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  world_countries: ^1.0.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  countries_world_map: ^1.1.1
  app_bar_with_search_switch: ^1.7.0
  hive: ^2.2.3
  admiralui: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true